WIP: 2258 display dynamic countries in the side bar
globaldothealth/react pull request #7
Opened 2021-12-07 15:51 UTC by sergioloporto

2021-12-08 13:04 UTC, maciekz1996 requested changes
Fetching total number of cases and displaying fetched countries looks and works well 👍 There are however few things that I noticed apart from the comments that I left:

- Total number of cases in Sidebar is hardcoded and should be dynamic
- The autocomplete feature doesn't work. After selecting a country still all other countries are visible
- After clicking on a country name map is not zooming to selected country 
- There are no loading indicators in the sidebar, so when the app is loading for the first time the Sidebar is mostly blank. It would be best to add some animated `Skeletons` from `mui` library
- I also noticed that in the current application there is a button at the bottom of the Sidebar. We should add the same button in this application (you can see the screenshot below)

<img width="373" alt="Screen Shot 2021-12-08 at 13 54 27" src="https://user-images.githubusercontent.com/44740625/145213058-a8fa3c05-ffaf-41ae-ad1c-1014ce8f0b8e.png">

2021-12-08 15:45 UTC, sergioloporto commented on src/models/VariantsData.ts
> -    location_id: string;
To make it more human readable, it is now ordered alphabetically

2021-12-13 12:40 UTC, maciekz1996 approved these changes
Great job, the code looks good and the functionality works as expected 🥇 There are two minor comments that I left, but other than that it can be merged. One missing thing though is Cypress tests, maybe it would be a good idea to create a new task for that.

2021-12-13 12:40 UTC, maciekz1996 commented on cypress/plugins/index.js
> +/// <reference types="cypress" />
I think this file can be deleted completely as we are not using it

2021-12-13 12:40 UTC, maciekz1996 commented on src/components/SideBar/index.tsx
> +                href="https://data.covid-19.global.health/"
This url should be replaced with `.env` variable in order to use appropriate links in Dev and Prod environments

2021-12-13 12:42 UTC, maciekz1996 requested changes
Oh actually I've just noticed that there is on functionality missing: 
After a user goes to other views like "Regional view" or "Coverage view" then "Fly to country" functionality is not working. All you have to do is to duplicate this functionality across all views 👍

2021-12-14 07:46 UTC, maciekz1996 approved these changes

2021-12-14 09:23 UTC, merged